# Inputs
---

In [1]:
import numpy as np, zarr, nrrd
# alignment functions
from bigstream.align import alignment_pipeline
from bigstream.transform import apply_transform
import tifffile

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
p = '/u/home/f/f7xiesnm/project-zipursky/code/BigStitcher-Spark/demo_small_xml'
outdir = '/u/home/f/f7xiesnm/project-zipursky/easifish/results/viz_fuse'
!mkdir -p $outdir

In [10]:
fix_path = p + '/dataset.n5'
fix_out = outdir + '/demo_small_raw.tiff'
fix_zarr = zarr.open(store=zarr.N5Store(fix_path), mode='r')
fix = fix_zarr['setup0/timepoint0/s0']

In [17]:
# fus_path = p + '/fused.n5'
fus_path = p + '/fused.n5'
fus_out = outdir + '/demo_small_c3_s3_fused.tiff'
fus_zarr = zarr.open(store=zarr.N5Store(fus_path), mode='r')
fus = fus_zarr['c1/s2']
# fus = fus_zarr['/c0/s0'][::8,::8,::8]

In [18]:
fix.shape, fus.shape

((211, 480, 480), (389, 480, 921))

In [19]:
fus[0,:,:]

array([[47225, 41112, 41108, ..., 41045, 41043, 41046],
       [41131, 32988, 32977, ..., 32885, 32881, 32884],
       [41131, 33000, 33011, ..., 32880, 32880, 32883],
       ...,
       [41054, 32900, 32903, ..., 33015, 33068, 33021],
       [41053, 32897, 32895, ..., 32998, 33035, 33022],
       [41053, 32890, 32889, ..., 33004, 32990, 32972]], dtype=uint16)

In [20]:
fus[1,:,:]

array([[28925, 16697, 16687, ..., 16555, 16550, 16554],
       [16731,   443,   428, ...,   234,   225,   231],
       [16734,   473,   495, ...,   227,   226,   234],
       ...,
       [16574,   262,   270, ...,   490,   574,   520],
       [16573,   259,   260, ...,   454,   521,   510],
       [16574,   247,   245, ...,   472,   454,   423]], dtype=uint16)

In [21]:
fus[2,:,:]

array([[28930, 16701, 16696, ..., 16557, 16548, 16554],
       [16725,   446,   439, ...,   231,   231,   231],
       [16727,   484,   500, ...,   227,   222,   228],
       ...,
       [16572,   258,   283, ...,   488,   546,   518],
       [16573,   253,   262, ...,   449,   506,   505],
       [16570,   250,   248, ...,   481,   456,   430]], dtype=uint16)

In [22]:
from scipy.stats import mode

In [23]:
mode(fus, axis=None)

ModeResult(mode=array([271], dtype=uint16), count=array([2574749]))

In [18]:
# np.min(fus), np.max(fus), mode(fus, axis=None)

In [19]:
# np.min(fix), np.max(fix), mode(fix, axis=None)

In [11]:
fix_out = outdir + '/demo_small_c1_s2_v2.tiff'
fix = fix_zarr['setup0/timepoint0/s2']
tifffile.imwrite(fix_out, fix) # fus)

In [20]:
fus_out = outdir + '/demo_small_c3_s3_fused_v2.tiff'
# fus = fus_zarr['c1/s3']
tifffile.imwrite(fus_out, a) # fus)

In [63]:
fus_out = outdir + '/lt172_c0_s3_fused.tiff'
fus = fus_zarr['c0/s3']
tifffile.imwrite(fus_out, fus)